name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - run: npm ci
    - run: npx hardhat compile
    - run: npx hardhat test
    - run: npx solhint 'contracts/**/*.sol'
    - run: npx hardhat coverage

  slither:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Slither
        uses: crytic/slither-action@v0.1.1
